name: dbt CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: dbt-logs
          path: logs/

      - name: Install requirements
        run: pip install dbt-core dbt-snowflake

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt test
        run:  dbt test --profiles-dir ./

      - name: Run dbt run
        run:  dbt run --profiles-dir ./
      
      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{
            github.ref == 'refs/heads/main' && secrets.AWS_ACCESS_KEY_ID_PRD ||
            github.ref == 'refs/heads/dev' && secrets.AWS_ACCESS_KEY_ID_DEV 
          }}

          aws-secret-access-key: ${{
            github.ref == 'refs/heads/main' && secrets.AWS_SECRET_ACCESS_KEY_ID_PRD ||
            github.ref == 'refs/heads/dev' && secrets.AWS_SECRET_ACCESS_KEY_ID_DEV 
          }}

          aws-region: us-east-1

      - name: Install Aws CLI
        run: sudo apt-get install -y awscli
        
      
      - name: Upload dbt project to s3
        run: aws s3 sync . s3://test-dbt-demo/  --exclude ".git/*"

          
      



